import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { PropsWithChildren } from 'react';
import useServerDarkMode from '@/hooks/useServerDarkMode';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: {
    template: '%s | Finance App',
    default: 'Finance App',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  // This is although a custom hook but working in server side only
  const theme = useServerDarkMode();
  return (
    <html lang="en" className={theme}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col`}
      >
        {children}
      </body>
    </html>
  );
}
